name             'midokura'
maintainer       'Vic Iglesias'
maintainer_email 'viglesias@eucalyptus.com'
license          'BSD'
description      'Installs/Configures midokura'
long_description 'Installs/Configures midokura'
version          '0.1.0'
depends          'java'
depends          'yum-epel'
depends          'cassandra'
#depends		 'thrift'
#depends		 'tomcat'
supports         'centos'
